### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by alexisgahon** [mikedisbrow/codecademy-atom-ui#1]
I have an error when trying to switch on this theme:
/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:126 Enabled theme 'codecademy-atom-ui' is not installed.

I don't know if I am doing things right.
I extract the zip download from this repo inside ~/.atom/packages

**Comment by mikedisbrow** [comment]
I will look into this and see if I can find any issue.  But I believe, to install a package or theme for Atom, you have to do it one of two ways.  With apm from the command line.  Or within the Settings > Install page in Atom.

https://atom.io/docs/latest/using-atom-atom-packages  

I think that should clear up your issue.

Thanks

**Comment by alexisgahon** [comment]
I tried to install it directly from atom and it worked.
Why ? Because when you download from github you have a folder named 

> **codecademy-atom-ui-master** (and it should be **codecademy-atom-syntax**)

So don't waste time on that, was my mistake, it works perfectly.

Thanks for you reply!
